name: Compile SA-MP PWN

on:
  push:
    paths:
      - "gamemodes/*.pwn"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar c√≥digo
        uses: actions/checkout@v3

      - name: Baixar Pawn Compiler
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://github.com/Zeex/pawn/releases/download/v3.10.10/pawnc-3.10.10-linux.zip
          unzip pawnc-3.10.10-linux.zip

      - name: Compilar PWN
        run: |
          chmod +x pawncc
          ./pawncc gamemodes/main.pwn -i include -o gamemodes/main.amx

      - name: Salvar AMX
        uses: actions/upload-artifact@v3
        with:
          name: compiled-amx
          path: gamemodes/main.amx
